import type { NextPage } from 'next';
import Head from 'next/head';

import TestForm from '../components/TestForm';
import TestList from '../components/TestList';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Hello World</h1>
      <TestForm />
      <TestList />
    </div>
  );
};

export default Home;
